<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new comment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('rss', array('action' => 'addfeedcomment')));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('author'));
echo $this->formRow($form->get('comment'));
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();