<?php
// module/Album/view/album/album/index.phtml:

$title = 'Some Comments';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('rss', array(
        'action'=>'addfeedcomment'));?>">Add new comment</a></p>

<table class="table">
<!--<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>-->
    //lololololo ssd j j
    //now i added this dummy line
<?php foreach($rssComments as $rssComment) : ?>
<tr>
    <td><?php echo $this->escapeHtml($rssComment->author);?></td>
    <td><?php echo $this->escapeHtml($rssComment->comment);?></td>
    <td><?php echo $this->escapeHtml($rssComment->email);?></td>
    <!--<td>
        <a href="<?php /*echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));*/?>">Edit</a>
        <a href="<?php /*echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));*/?>">Delete</a>
    </td>-->
</tr>
<?php endforeach; ?>
</table>